name = "divmemory"
main = "src/index.ts"
compatibility_date = "2025-04-10"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[[d1_databases]]
binding = "DB"
database_name = "divmemory-db"
database_id = "601afc4d-c4f3-4392-aa67-c413671d61e2"
